# DAY 3 ASSIGNMENT 

## Question 1:

###  Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np 
print(np.arange(2, 50, 3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question 2:

### Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy
First_list = int(input("Enter the size of list "))
print("\n")
numList_1 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:First_list]
print("First List: ", numList_1)
print("\n")
Second_list = int(input("Enter the size of list "))
print("\n")
numList_2 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:Second_list]
print("Second List: ", numList_2)
print("\n")
Array_1 = numpy.array(numList_1)
Array_2 = numpy.array(numList_2)

print("Array1 as Numpy_Array ",Array_1)
print("Array2 as Numpy_Array ",Array_2)
print("\n")

Concatenated_array = numpy.concatenate((Array_1, Array_2), axis=0)
print("Concatenated array ", Concatenated_array)
print("\n")
Concatenated_array.sort()
print("Sorted Array ", Concatenated_array)

Enter the size of list 6


Enter the list numbers separated by space 5 8 9 6 2 3 
First List:  [5, 8, 9, 6, 2, 3]


Enter the size of list 6


Enter the list numbers separated by space 8 9 5 4 7 2
Second List:  [8, 9, 5, 4, 7, 2]


Array1 as Numpy_Array  [5 8 9 6 2 3]
Array2 as Numpy_Array  [8 9 5 4 7 2]


Concatenated array  [5 8 9 6 2 3 8 9 5 4 7 2]


Sorted Array  [2 2 3 4 5 5 6 7 8 8 9 9]


## Question 3:

### Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
arr2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print('2D Numpy Array')
print(arr2D)
print("\n")
numOfRows = np.size(arr2D, 0)
numOfColumns = np.size(arr2D, 1)
print('Number of Rows : ', numOfRows)
print('Number of Columns : ', numOfColumns)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]


Number of Rows :  3
Number of Columns :  4


## Quesion 4:

###  How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)
print("\n")
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print("2D Array ")
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]


2D Array 
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question 5:

### Consider two square numpy arrays. Stack them vertically and horizontally.

In [5]:
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


## Question 6:

### How to get unique items and counts of unique items?

In [6]:
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x))  
list1 = [10, 20, 10, 30, 40, 40] 
print("The unique values from 1st list is") 
unique(list1) 
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[10 20 30 40]
No of unique items in the list are: 4
